#!/bin/bash

function install() {
  readonly installPath="/usr/local/bin/nitch"

  chmod +x "$fileName"
  sudo mv "$fileName" "$installPath"

  printf "%s\n" "Nitch installed correctly."
}

function downloadFile() {
  local url="https://api.github.com/repos/gabrielcapilla/nitch/releases/latest"
  local downloadUrl
  downloadUrl=$(curl -s "$url" | jq -r ".assets[] | select(.name == \"$fileName\") | .browser_download_url")

  if [ -n "$downloadUrl" ]; then
    curl -L -o "$fileName" "$downloadUrl"
    install
  else
    printf "%s\n" "The file '$fileName' could not be found in the provided URL."
  fi
}

function installNitch() {
  read -r -p "Install Nitch? (y/n): " choice
  choice=$(echo "$choice" | tr '[:upper:]' '[:lower:]')

  case $choice in
  "y")
    readonly fileName="nitch"
    downloadFile
    ;;
  "n" | *) exit 0 ;;
  esac
}

function main() {
  local installDir="/usr/local/bin"
  local file="nitch"

  if [ -f "$installDir/$file" ]; then
    read -r -p "Upgrade '$file'? (y/n): " upgradeNitch

    case $upgradeNitch in
    "y")
      readonly fileName="nitch"
      downloadFile
      ;;
    "n" | *) exit 0 ;;
    esac
  else
    installNitch
  fi
}

main
